name: "Audit"
on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/*'
  schedule:
    - cron: '09 22 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: npm version
    - run: npm ci
    - run: npm audit --audit-level=moderate
